[build]
builder = "nixpacks"

[variables]
NODE_VERSION = "18"

[deploy]
startCommand = "cd monolithic && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[phases.setup]
aptPkgs = ["nodejs", "npm", "openssl"]

[phases.install]
workingDirectory = "monolithic"
cmds = ["npm install"]

[phases.build]
workingDirectory = "monolithic"
cmds = ["npm run build"]