[phases.setup]
nixpkgs = ['nodejs', 'yarn', 'openssl']

[phases.install]
cmds = ['cd monolithic && npm install']

[phases.build]
cmds = ['cd monolithic && npm run build']

[start]
cmd = 'cd monolithic && npm run start:prod'

[deploy]
startCommand = 'cd monolithic && npm run start:prod'
restartPolicyType = 'ON_FAILURE'
restartPolicyMaxRetries = 3